# Generated by Django 2.0.5 on 2018-05-29 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iho', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.ManyToManyField(help_text='Select a category for this item.', to='iho.Category'),
        ),
    ]
