# Generated by Django 2.0.5 on 2018-06-01 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iho', '0003_document_examplemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document',
            field=models.ImageField(upload_to='iho/'),
        ),
    ]
